name: "💡 Feature Request"
description: Create a ticket for a new feature request
title: "Request: "
labels: ["feature-request"]

body:
  - type: textarea
    id: summary
    attributes:
      label: "Summary"
      description: Provide a brief explanation of your feature request
      placeholder: Describe in a few lines your feature request
    validations:
      required: true

  - type: textarea
    id: basic_example
    attributes:
      label: "Basic Example"
      description: Indicate here some basic examples of your feature.
      placeholder: A few specific words about your feature request.
    validations:
      required: true
  
  - type: dropdown
    id: platform
    attributes:
      label: Is this specific to a text editor?
      multiple: true
      options:
        - VSCode
        - Sublime Text
        - Other (please specify above)
    validations:
      required: false

  - type: textarea
    id: other-info
    attributes:
      label: "Other Info"
      description: Any drawbacks or other details of your feature request?
      placeholder: Other thoughts you think might be **Important**
      render: bash
    validations:
      required: false
